In [1]:
import numpy as np

#Problem 1

In [30]:
A =np.array([
    [[[23,50], [7,12]],
     [[75,21], [57,12]]],
    [[[57,67], [99,43]],
     [[87,26], [18,84]]]
])

In [31]:
print(A)

[[[[23 50]
   [ 7 12]]

  [[75 21]
   [57 12]]]


 [[[57 67]
   [99 43]]

  [[87 26]
   [18 84]]]]


#Problem 2

In [32]:
A = np.array([
              [23, 50, 19],
              [7, 12, 109],
              [57, 67, 98]
])
B= np.array([17, 22, 19])

In [38]:
result = A.dot(B)
result

array([1852, 2454, 4305])

#Problem 3

In [39]:
A = np.array([
              [23, 50, 19],
              [7, 12, 109],
              [57, 67, 98]
])

In [40]:
#Transpose
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [51]:
#Determinan
B = np.linalg.det(A)
print(B)


131344.0000000002


In [52]:
#Inverse
C = np.linalg.inv(A)
print(C)

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
